"""
Script which manages HDF5 files generated by RIPTIDE.
Kenil Ajudiya <kenilr@iisc.ac.in>

+-----------------------------------------------------------------------------------------+
+                       PLEASE RECORD ANY MODIFICATIONS YOU MAKE BELOW                    +
+-----------------------------------------------------------------------------------------+
+ Revision |     Author      | Description                                   |    DATE    +
+-----------------------------------------------------------------------------------------+

 Revision:0   Kenil Ajudiya    Initial version of code.                        19/11/2025
"""

# Standard library Imports:
import sys
from numpy import mean
from numpy import std
from scipy.stats import skew
from scipy.stats import kurtosis
from h5py import File

# Custom file Imports:
from Utilities import Utilities

# ****************************************************************************************************
#
# CLASS DEFINITION
#
# ****************************************************************************************************

class HDF5(Utilities):
    """
    Represents a HDF5 file, generated by RIPTIDE.
    """
    
    # ****************************************************************************************************
    #
    # Constructor.
    #
    # ****************************************************************************************************
    
    def __init__(self,candidateName):
        """
        Default constructor.
        
        Parameters:
        
        candidateName -    the name for the candidate, typically the file path.
        """
        self.cand = candidateName
        self.load()

    # ****************************************************************************************************
           
    def load(self):
        """
        Attempts to load candidate data from the file.
        
        Parameters:
        N/A
        
        Return:
        N/A
        """
        with File(self.cand, "r") as f:
            self.dm_curve_snr = f['response_curves/dm_curve_snr'][:]
            # self.dm_curve_trials = f['response_curves/dm_curve_trials'][:]
            # self.period_curve_snr = f['response_curves/period_curve_snr'][:]
            # self.period_curve_trials = f['response_curves/period_curve_trials'][:]
            # self.width_curve_snr = f['response_curves/width_curve_snr'][:]
            # self.width_curve_trials = f['response_curves/width_curve_trials'][:]
            self.data = f['subints/data'][:]
            self.profile = self.data.mean(axis=0)

    # ****************************************************************************************************

    def computeProfileStatScores(self):
        """
        Builds the stat scores using raw profile intensity data only. Returns the scores.
        
        Parameters:
        N/A
        
        Returns:
        Returns a list of statistics derived from the candidate's profile.
        """
        
        try:
            return [mean(self.profile),std(self.profile),skew(self.profile),kurtosis(self.profile)]
        except Exception as e: # catch *all* exceptions
            print("Error getting Profile stat scores from HDF5 file\n\t", sys.exc_info()[0])
            print(self.format_exception(e))
            raise Exception("Profile stat score extraction exception")
    
    def computeDMCurveStatScores(self):
        """
        Builds the stat scores using DM curve SNR data only. Returns the scores.
        
        Parameters:
        N/A
        
        Returns:
        Returns a list of statistics derived from the candidate's DM curve.
        """
        
        try:
            return [mean(self.dm_curve_snr),std(self.dm_curve_snr),skew(self.dm_curve_snr),kurtosis(self.dm_curve_snr)]
        except Exception as e: # catch *all* exceptions
            print("Error getting DM curve stat scores from HDF5 file\n\t", sys.exc_info()[0])
            print(self.format_exception(e))
            raise Exception("DM curve stat score extraction exception")
        
    # ****************************************************************************************************