"""
Script which manages HDF5 files generated by RIPTIDE.
Kenil Ajudiya <kenilr@iisc.ac.in>

+-----------------------------------------------------------------------------------------+
+                       PLEASE RECORD ANY MODIFICATIONS YOU MAKE BELOW                    +
+-----------------------------------------------------------------------------------------+
+ Revision |     Author      | Description                                   |    DATE    +
+-----------------------------------------------------------------------------------------+

 Revision:0   Kenil Ajudiya    Initial version of code.                        19/11/2025
"""

import sys, logging
from numpy import mean
from numpy import std
from scipy.stats import skew
from scipy.stats import kurtosis
from h5py import File

from Utilities import Utilities

class HDF5(Utilities):
    """
    Represents a HDF5 file, generated by RIPTIDE.
    """
    
    def __init__(self, candidateName: str, logger_name: str):
        """
        Default constructor.
        
        Parameters:
        
        candidateName -    the name for the candidate, typically the file path.
        """
        self.cand = candidateName
        self.logger = logging.getLogger(logger_name)
        self.load()

    # ****************************************************************************************************
           
    def load(self):
        """
        Attempts to load candidate data from the file.
        
        Parameters:
        N/A
        
        Return:
        N/A
        """
        with File(self.cand, "r") as f:
            # self.dm_curve_snr = f['response_curves/dm_curve_snr'][:]
            self.dm_curve_trials = f['response_curves/dm_curve_trials'][:]
            # self.period_curve_snr = f['response_curves/period_curve_snr'][:]
            # self.period_curve_trials = f['response_curves/period_curve_trials'][:]
            # self.width_curve_snr = f['response_curves/width_curve_snr'][:]
            # self.width_curve_trials = f['response_curves/width_curve_trials'][:]
            self.data = f['subints/data'][:]
            self.profile = self.data.mean(axis=0)

    # ****************************************************************************************************

    def computeProfileStatScores(self):
        """
        Builds the stat scores using raw profile intensity data only. Returns the scores.
        
        Parameters:
        N/A
        
        Returns:
        Returns a list of statistics derived from the candidate's profile.
        """
        
        try:
            return [mean(self.profile),std(self.profile),skew(self.profile),kurtosis(self.profile)]
        except Exception as e: # catch *all* exceptions
            self.logger.error("Error getting Profile stat scores from HDF5 file\n\t%s", sys.exc_info()[0])
            self.logger.error(self.format_exception(e))
            raise Exception("Profile stat score extraction exception")
    
    def computeDMCurveStatScores(self):
        """
        Builds the stat scores using DM curve SNR data only. Returns the scores.
        
        Parameters:
        N/A
        
        Returns:
        Returns a list of statistics derived from the candidate's DM curve.
        """
        
        try:
            return [mean(self.dm_curve_trials),std(self.dm_curve_trials),skew(self.dm_curve_trials),kurtosis(self.dm_curve_trials)]
        except Exception as e: # catch *all* exceptions
            self.logger.error("Error getting DM curve stat scores from HDF5 file\n\t%s", sys.exc_info()[0])
            self.logger.error(self.format_exception(e))
            raise Exception("DM curve stat score extraction exception")
        
    # ****************************************************************************************************